### ISSUE TITLE
Add `key` property to each child in Dropdown

### ISSUE THREAD

**Issue by focacci** [focacci/relay-network-take-home-michael-focacci#19]
The browser debug console displays this warning:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Dropdown`. See https://reactjs.org/link/warning-keys for more information.
    at option
    at Dropdown (http://localhost:3000/static/js/bundle.js:186:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:33:74)
```

This is saying that each option object generated in `src/Dropdown.js:8-10` should contain a unique key prop:
```
                {options.map((option) => (
                    <option value={option.value}>{option.label}</option>
                ))}
```

**Comment by focacci** [comment]
Acceptance test:

1. Run the application with `npm start`
2. Go to the browser and open `localhost:3000`
3. View debug console
4. Verify the above error message is not displayed
