### ISSUE TITLE
Add `key` property to each child in TableBody

### ISSUE THREAD

**Issue by focacci** [focacci/relay-network-take-home-michael-focacci#20]
The browser debug console displays this warning:

```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at TableBody (http://localhost:3000/static/js/bundle.js:411:5)
    at tbody
    at table
    at div
    at Table (http://localhost:3000/static/js/bundle.js:507:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:33:74)
```

This is saying that each object generated in `src/Table.js:8-28` should contain a unique key prop:
```
            rows.map(row =>
                {
                    return (
                        <tr>
                            <td>{row["ward"]}</td>
                            <td>{row["rep"]}</td>
                            <td>{row["dem"]}</td>
                            <td>{row["other_party"]}</td>
                            <td>{row["male"]}</td>
                            <td>{row["female"]}</td>
                            <td>{row["unknown_sex"]}</td>
                            <td>{row["black"]}</td>
                            <td>{row["hispanic"]}</td>
                            <td>{row["white"]}</td>
                            <td>{row["other_race"]}</td>
                            <td>{row["total"]}</td>
                            <td>{(segment === "") ? "%" : formatAsPercent((row[segment]/row["total"])*100)}</td>
                        </tr> 
                    )
                }
            )
```

**Comment by focacci** [comment]
Acceptance test:

1. Run the application with `npm start`
2. Go to the browser and open `localhost:3000`
3. View debug console
4. Verify the above error message is not displayed
